{% set name = "python-logstash-async" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d036bb0433cdedb5d040366bc4240b3e2c2436cdf860ef2f0e7dabee1cc1b44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - limits
    - pylogbeat
    - requests
    - python >=3.6

test:
  imports:
    - logstash_async
    - logstash_async.worker

about:
  home: https://github.com/eht16/python-logstash-async
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Asynchronous Python logging handler for Logstash.
  doc_url: https://python-logstash-async.readthedocs.io/en/latest/
  dev_url: https://github.com/eht16/python-logstash-async

extra:
  recipe-maintainers:
    - tiefling-cat
